# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=20)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.Area')),
            ],
        ),
    ]
