# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20181121_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='boarding',
            name='price',
        ),
        migrations.RemoveField(
            model_name='grooming',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='grooming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.Grooming'),
        ),
        migrations.AddField(
            model_name='care',
            name='boarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cares', to='services.Boarding'),
        ),
    ]
