# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20181121_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='care',
            name='boarding',
        ),
        migrations.RemoveField(
            model_name='service',
            name='grooming',
        ),
        migrations.AddField(
            model_name='boarding',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grooming',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Care',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
